export const supportedCryptos = [
  { symbol: "1INCHUSDT", acronym: "1INCH", name: "1inch", supply: 1_500_000_000, logo: "https://cryptologos.cc/logos/1inch-1inch-logo.svg" },
  { symbol: "AAVEUSDT", acronym: "AAVE", name: "Aave", supply: 16_000_000, logo: "https://cryptologos.cc/logos/aave-aave-logo.svg" },
  { symbol: "ACTUSDC", acronym: "ACT", name: "Achain", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/achain-act-logo.svg" },
  { symbol: "ADAUSDC", acronym: "ADA", name: "Cardano", supply: 45_000_000_000, logo: "https://cryptologos.cc/logos/cardano-ada-logo.svg" },
  { symbol: "ALGOUSDC", acronym: "ALGO", name: "Algorand", supply: 10_000_000_000, logo: "https://cryptologos.cc/logos/algorand-algo-logo.svg" },
  { symbol: "ALTUSDC", acronym: "ALT", name: "AltLayer", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/altlayer-alt-logo.svg" },
  { symbol: "APTUSDC", acronym: "APT", name: "Aptos", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/aptos-apt-logo.svg" },
  { symbol: "ARBUSDC", acronym: "ARB", name: "Arbitrum", supply: 10_000_000_000, logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.svg" },
  { symbol: "ARUSDC", acronym: "AR", name: "Arweave", supply: 66_000_000, logo: "https://cryptologos.cc/logos/arweave-ar-logo.svg" },
  { symbol: "ATOMUSDC", acronym: "ATOM", name: "Cosmos", supply: 286_370_297, logo: "https://cryptologos.cc/logos/cosmos-atom-logo.svg" },
  { symbol: "AVAXUSDC", acronym: "AVAX", name: "Avalanche", supply: 720_000_000, logo: "https://cryptologos.cc/logos/avalanche-avax-logo.svg" },
  { symbol: "AXSUSDT", acronym: "AXS", name: "Axie Infinity", supply: 270_000_000, logo: "https://cryptologos.cc/logos/axie-infinity-axs-logo.svg" },
  { symbol: "BNBUSDC", acronym: "BNB", name: "Binance Coin", supply: 192_443_301, logo: "https://cryptologos.cc/logos/binance-coin-bnb-logo.svg" },
  { symbol: "BCHUSDC", acronym: "BCH", name: "Bitcoin Cash", supply: 21_000_000, logo: "https://cryptologos.cc/logos/bitcoin-cash-bch-logo.svg" },
  { symbol: "BTCUSDC", acronym: "BTC", name: "Bitcoin", supply: 21_000_000, logo: "https://cryptologos.cc/logos/bitcoin-btc-logo.svg" },
  { symbol: "CGPTUSDC", acronym: "CGPT", name: "ChainGPT", supply: 1_000_000_000, logo: "https://cdn.prod.website-files.com/64354b8ce4872ad8cd1c7b04/653ba24987df35fe63c92a17_chaingpt-logo-head.svg" },
  { symbol: "CHZUSDC", acronym: "CHZ", name: "Chiliz", supply: 8_888_888_888, logo: "https://cryptologos.cc/logos/chiliz-chz-logo.svg" },
  { symbol: "COMPUSDT", acronym: "COMP", name: "Compound", supply: 10_000_000, logo: "https://cryptologos.cc/logos/compound-comp-logo.svg" },
  { symbol: "DOGEUSDC", acronym: "DOGE", name: "Dogecoin", supply: 148_000_000_000, logo: "https://cryptologos.cc/logos/dogecoin-doge-logo.svg" },
  { symbol: "DOTUSDC", acronym: "DOT", name: "Polkadot", supply: 1_103_303_471, logo: "https://cryptologos.cc/logos/polkadot-new-dot-logo.svg" },
  { symbol: "DYDXUSDC", acronym: "DYDX", name: "dYdX", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/dydx-dydx-logo.svg" },
  { symbol: "ENJUSDT", acronym: "ENJ", name: "Enjin Coin", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/enjin-coin-enj-logo.svg" },
  { symbol: "EOSUSDC", acronym: "EOS", name: "EOS", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/eos-eos-logo.svg" },
  { symbol: "ETHUSDC", acronym: "ETH", name: "Ethereum", supply: 122_373_866, logo: "https://cryptologos.cc/logos/ethereum-eth-logo.svg" },
  { symbol: "FILUSDC", acronym: "FIL", name: "Filecoin", supply: 1_971_421_056, logo: "https://cryptologos.cc/logos/filecoin-fil-logo.svg" },
  { symbol: "GALAUSDC", acronym: "GALA", name: "Gala", supply: 50_000_000_000, logo: "https://cryptologos.cc/logos/gala-gala-logo.svg" },
  { symbol: "GRTUSDT", acronym: "GRT", name: "The Graph", supply: 10_000_000_000, logo: "https://cryptologos.cc/logos/the-graph-grt-logo.svg" },
  { symbol: "HBARUSDC", acronym: "HBAR", name: "Hedera Hashgraph", supply: 50_000_000_000, logo: "https://cryptologos.cc/logos/hedera-hbar-logo.svg" },
  { symbol: "ICPUSDC", acronym: "ICP", name: "Internet Computer", supply: 530_100_000, logo: "https://cryptologos.cc/logos/internet-computer-icp-logo.svg" },
  { symbol: "JUPUSDC", acronym: "JUP", name: "Jupiter", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/jupiter-ag-jup-logo.svg" },
  { symbol: "KAVAUSDT", acronym: "KAVA", name: "Kava", supply: 401_000_000, logo: "https://cryptologos.cc/logos/kava-kava-logo.svg" },
  { symbol: "LINKUSDC", acronym: "LINK", name: "Chainlink", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/chainlink-link-logo.svg" },
  { symbol: "LTCUSDC", acronym: "LTC", name: "Litecoin", supply: 84_000_000, logo: "https://cryptologos.cc/logos/litecoin-ltc-logo.svg" },
  { symbol: "NEARUSDC", acronym: "NEAR", name: "Near Protocol", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/near-protocol-near-logo.svg" },
  { symbol: "OMUSDC", acronym: "OM", name: "MANTRA", supply: 888_888_888, logo: "https://cryptologos.cc/logos/mantra-om-logo.svg" },
  { symbol: "RUNEUSDC", acronym: "RUNE", name: "THORChain", supply: 500_000_000, logo: "https://cryptologos.cc/logos/thorchain-rune-logo.svg" },
  { symbol: "SANDUSDC", acronym: "SAND", name: "The Sandbox", supply: 3_000_000_000, logo: "https://cryptologos.cc/logos/the-sandbox-sand-logo.svg" },
  { symbol: "SHIBUSDC", acronym: "SHIB", name: "SHIBA INU", supply: 589_253_856_174_601, logo: "https://cryptologos.cc/logos/shiba-inu-shib-logo.svg" },
  { symbol: "SOLUSDC", acronym: "SOL", name: "Solana", supply: 511_616_946, logo: "https://cryptologos.cc/logos/solana-sol-logo.svg" },
  { symbol: "SUIUSDC", acronym: "SUI", name: "Sui", supply: 10_000_000_000, logo: "https://cryptologos.cc/logos/sui-sui-logo.svg" },
  { symbol: "TAOUSDC", acronym: "TAO", name: "Bittensor", supply: 21_000_000, logo: "https://cryptologos.cc/logos/bittensor-tao-logo.svg" },
  { symbol: "TONUSDC", acronym: "TON", name: "Toncoin", supply: 5_000_000_000, logo: "https://cryptologos.cc/logos/toncoin-ton-logo.svg" },
  { symbol: "TRXUSDC", acronym: "TRX", name: "Tron", supply: 86_090_409_184, logo: "https://cryptologos.cc/logos/tron-trx-logo.svg" },
  { symbol: "UNIUSDC", acronym: "UNI", name: "Uniswap", supply: 1_000_000_000, logo: "https://cryptologos.cc/logos/uniswap-uni-logo.svg" },
  { symbol: "VETUSDT", acronym: "VET", name: "VeChain", supply: 86_712_634_466, logo: "https://cryptologos.cc/logos/vechain-vet-logo.svg" },
  { symbol: "XLMUSDC", acronym: "XLM", name: "Stellar", supply: 50_001_806_812, logo: "https://cryptologos.cc/logos/stellar-xlm-logo.svg" },
  { symbol: "XRPUSDC", acronym: "XRP", name: "Ripple", supply: 100_000_000_000, logo: "https://cryptologos.cc/logos/xrp-xrp-logo.svg" },
  { symbol: "XTZUSDC", acronym: "XTZ", name: "Tezos", supply: 1_050_000_000, logo: "https://cryptologos.cc/logos/tezos-xtz-logo.svg" },
  { symbol: "ZECUSDT", acronym: "ZEC", name: "Zcash", supply: 21_000_000, logo: "https://cryptologos.cc/logos/zcash-zec-logo.svg" },

];
