export const supportedCryptos = [
  { symbol: "1INCHUSDT", acronym: "1INCH", name: "1inch", logo: "https://cryptologos.cc/logos/1inch-1inch-logo.svg" },
  { symbol: "AAVEUSDT", acronym: "AAVE", name: "Aave", logo: "https://cryptologos.cc/logos/aave-aave-logo.svg" },
  { symbol: "ACTUSDC", acronym: "ACT", name: "Achain", logo: "https://cryptologos.cc/logos/achain-act-logo.svg" },
  { symbol: "ADAUSDC", acronym: "ADA", name: "Cardano", logo: "https://cryptologos.cc/logos/cardano-ada-logo.svg" },
  { symbol: "ALGOUSDC", acronym: "ALGO", name: "Algorand", logo: "https://cryptologos.cc/logos/algorand-algo-logo.svg" },
  { symbol: "ALTUSDC", acronym: "ALT", name: "AltLayer", logo: "https://cryptologos.cc/logos/altlayer-alt-logo.svg" },
  { symbol: "APTUSDC", acronym: "APT", name: "Aptos", logo: "https://cryptologos.cc/logos/aptos-apt-logo.svg" },
  { symbol: "ARBUSDC", acronym: "ARB", name: "Arbitrum", logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.svg" },
  { symbol: "ARUSDC", acronym: "AR", name: "Arweave", logo: "https://cryptologos.cc/logos/arweave-ar-logo.svg" },
  { symbol: "ATOMUSDC", acronym: "ATOM", name: "Cosmos", logo: "https://cryptologos.cc/logos/cosmos-atom-logo.svg" },
  { symbol: "AVAXUSDC", acronym: "AVAX", name: "Avalanche", logo: "https://cryptologos.cc/logos/avalanche-avax-logo.svg" },
  { symbol: "AXSUSDT", acronym: "AXS", name: "Axie Infinity", logo: "https://cryptologos.cc/logos/axie-infinity-axs-logo.svg" },
  { symbol: "BNBUSDC", acronym: "BNB", name: "Binance Coin", logo: "https://cryptologos.cc/logos/binance-coin-bnb-logo.svg" },
  { symbol: "BCHUSDC", acronym: "BCH", name: "Bitcoin Cash", logo: "https://cryptologos.cc/logos/bitcoin-cash-bch-logo.svg" },
  { symbol: "BTCUSDC", acronym: "BTC", name: "Bitcoin", logo: "https://cryptologos.cc/logos/bitcoin-btc-logo.svg" },
  { symbol: "CGPTUSDC", acronym: "CGPT", name: "ChainGPT", logo: "https://cdn.prod.website-files.com/64354b8ce4872ad8cd1c7b04/653ba24987df35fe63c92a17_chaingpt-logo-head.svg" },
  { symbol: "CHZUSDC", acronym: "CHZ", name: "Chiliz", logo: "https://cryptologos.cc/logos/chiliz-chz-logo.svg" },
  { symbol: "COMPUSDT", acronym: "COMP", name: "Compound", logo: "https://cryptologos.cc/logos/compound-comp-logo.svg" },
  { symbol: "DOGEUSDC", acronym: "DOGE", name: "Dogecoin", logo: "https://cryptologos.cc/logos/dogecoin-doge-logo.svg" },
  { symbol: "DOTUSDC", acronym: "DOT", name: "Polkadot", logo: "https://cryptologos.cc/logos/polkadot-new-dot-logo.svg" },
  { symbol: "DYDXUSDC", acronym: "DYDX", name: "dYdX", logo: "https://cryptologos.cc/logos/dydx-dydx-logo.svg" },
  { symbol: "ENJUSDT", acronym: "ENJ", name: "Enjin Coin", logo: "https://cryptologos.cc/logos/enjin-coin-enj-logo.svg" },
  { symbol: "EOSUSDC", acronym: "EOS", name: "EOS", logo: "https://cryptologos.cc/logos/eos-eos-logo.svg" },
  { symbol: "ETHUSDC", acronym: "ETH", name: "Ethereum", logo: "https://cryptologos.cc/logos/ethereum-eth-logo.svg" },
  { symbol: "FILUSDC", acronym: "FIL", name: "Filecoin", logo: "https://cryptologos.cc/logos/filecoin-fil-logo.svg" },
  { symbol: "GALAUSDC", acronym: "GALA", name: "Gala", logo: "https://cryptologos.cc/logos/gala-gala-logo.svg" },
  { symbol: "GRTUSDT", acronym: "GRT", name: "The Graph", logo: "https://cryptologos.cc/logos/the-graph-grt-logo.svg" },
  { symbol: "HBARUSDC", acronym: "HBAR", name: "Hedera Hashgraph", logo: "https://cryptologos.cc/logos/hedera-hbar-logo.svg" },
  { symbol: "ICPUSDC", acronym: "ICP", name: "Internet Computer", logo: "https://cryptologos.cc/logos/internet-computer-icp-logo.svg" },
  { symbol: "JUPUSDC", acronym: "JUP", name: "Jupiter", logo: "https://cryptologos.cc/logos/jupiter-ag-jup-logo.svg" },
  { symbol: "KAVAUSDT", acronym: "KAVA", name: "Kava", logo: "https://cryptologos.cc/logos/kava-kava-logo.svg" },
  { symbol: "LINKUSDC", acronym: "LINK", name: "Chainlink", logo: "https://cryptologos.cc/logos/chainlink-link-logo.svg" },
  { symbol: "LTCUSDC", acronym: "LTC", name: "Litecoin", logo: "https://cryptologos.cc/logos/litecoin-ltc-logo.svg" },
  { symbol: "NEARUSDC", acronym: "NEAR", name: "Near Protocol", logo: "https://cryptologos.cc/logos/near-protocol-near-logo.svg" },
  { symbol: "OMUSDC", acronym: "OM", name: "MANTRA", logo: "https://cryptologos.cc/logos/mantra-om-logo.svg" },
  { symbol: "RUNEUSDC", acronym: "RUNE", name: "THORChain", logo: "https://cryptologos.cc/logos/thorchain-rune-logo.svg" },
  { symbol: "SANDUSDC", acronym: "SAND", name: "The Sandbox", logo: "https://cryptologos.cc/logos/the-sandbox-sand-logo.svg" },
  { symbol: "SHIBUSDC", acronym: "SHIB", name: "SHIBA INU", logo: "https://cryptologos.cc/logos/shiba-inu-shib-logo.svg" },
  { symbol: "SOLUSDC", acronym: "SOL", name: "Solana", logo: "https://cryptologos.cc/logos/solana-sol-logo.svg" },
  { symbol: "SUIUSDC", acronym: "SUI", name: "Sui", logo: "https://cryptologos.cc/logos/sui-sui-logo.svg" },
  { symbol: "TAOUSDC", acronym: "TAO", name: "Bittensor", logo: "https://cryptologos.cc/logos/bittensor-tao-logo.svg" },
  { symbol: "TONUSDC", acronym: "TON", name: "Toncoin", logo: "https://cryptologos.cc/logos/toncoin-ton-logo.svg" },
  { symbol: "TRXUSDC", acronym: "TRX", name: "Tron", logo: "https://cryptologos.cc/logos/tron-trx-logo.svg" },
  { symbol: "UNIUSDC", acronym: "UNI", name: "Uniswap", logo: "https://cryptologos.cc/logos/uniswap-uni-logo.svg" },
  { symbol: "VETUSDT", acronym: "VET", name: "VeChain", logo: "https://cryptologos.cc/logos/vechain-vet-logo.svg" },
  { symbol: "XLMUSDC", acronym: "XLM", name: "Stellar", logo: "https://cryptologos.cc/logos/stellar-xlm-logo.svg" },
  { symbol: "XRPUSDC", acronym: "XRP", name: "Ripple", logo: "https://cryptologos.cc/logos/xrp-xrp-logo.svg" },
  { symbol: "XTZUSDC", acronym: "XTZ", name: "Tezos", logo: "https://cryptologos.cc/logos/tezos-xtz-logo.svg" },
  { symbol: "ZECUSDT", acronym: "ZEC", name: "Zcash", logo: "https://cryptologos.cc/logos/zcash-zec-logo.svg" },
];